name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install black
      run: python -m pip install black
    - name: Test
      run: black --check .